---
version: "2.1"
services:
  ipfs:
    build:
      context: os/.
    container_name: ipfs
    environment:
    - IPFS_PATH="/ipfs_data/data"
    - IPFS_IP_ADDRESS="192.168.1.15"
    ports:
    - "4001:4001"
    - "4001:4001/udp"
    - "5001:5001"
    - "8080:8080"
    volumes:
    - /home/pi/dockerIpfs/data:/ipfs_data
